env_name: 'pretouch_mjrl-v0'
n_episodes: 1 #10
max_ep_length: 200
seed: 123
base_action: 'null'
render: True

mppi:
  horizon           : 20
  init_cov          : 0.2 #1.0
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 0.99
  n_iters           : 1
  step_size         : 1.0
  lam               : 0.2
  alpha             : 1
  num_cpu           : 10
  particles_per_cpu : 20
  base_action       : 'null'
  time_based_weights: False
  use_zero_control_seq: True
